### PR TITLE
Added support for TLS encrypted mail servers, updated code to be pep8...

### PR DESCRIPTION
**Pull request by jamver**
... compliant

### CODE REVIEW

**Comment by jamver** [comment]
added additional flag to expose cluster name to script

wsrep_notify_cmd='/path/to/galeranotify.py --cluster-name <cluster-name>'

**Comment by gguillen** [comment]
Where do you see that --cluster-name is now used for the wsrep_notify_cmd scripts?  I was just notified that Codership updated their documentation to match the latest Galera release, but the documentation at http://galeracluster.com/documentation-webpages/monitoringthecluster.html mentions no such command line option.

**Comment by gguillen** [comment]
Closed with no further info.

**Comment by jamver** [comment]
Sorry I missed the original request for further information.

--cluster-name is not used by wsrep_notify_cmd, I added it so I can use it across multiple clusters which may have nodes running on the same host on different ports so I can more accurately report on changes, e.g.

wsrep_notify_cmd                        = '/var/lib/mysql/galeranotify.py --cluster-name prod.dsk.au.yourdigitalfile'

**Comment by jamver** [comment]
Also, --cluster-name is not the only change in this pull request.  It includes additional support for TLS smtp servers.

**Comment by gguillen** [comment]
I like how you added TLS support in, but I think it is overly complex to predefine the ports and perform all the logic.  I would just prefer the simple port and "mode" (sudo-enum possibly?).  I might add this in a future version, but its not a priority at the moment.  At that point I'll also make it PEP8 compliant.

**Pull request closed without merging**
